### ISSUE TITLE
Bitcoin core accidentally reset

### ISSUE THREAD

**Issue by lajournalista** [bitcoin-core/gitian.sigs#1039]
My node was running in my MAC OS X computer that I accidentally reset. When trying to restart Core now it is not working.I'm wondering if there's a way for me to "rewind" back to a state before my computer crashed, so I don't have to resync the entire chain from scratch.
I am a beginner I need help.

**Comment by lajournalista** [comment]
[config.log](https://github.com/bitcoin-core/gitian.sigs/files/3245545/config.log)
[debug.log](https://github.com/bitcoin-core/gitian.sigs/files/3245561/debug.log)
I need help My bitcoin core now is not working I attached the files I don't know what to do.

**Comment by fanquake** [comment]
Please open an issue at https://github.com/bitcoin/bitcoin rather than here. Note that that repository is generally for technical issues, rather than user support, so you might also want to try asking questions on the bitcoin stack exchange: https://bitcoin.stackexchange.com/.
