### ISSUE TITLE
different hash for bitcoin-0.20.0rc1-osx-unsigned.tar.gz

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin-core/gitian.sigs#1222]
My macOS gitian build result for the unsigned tarball has a different hash than anyone else (see below).

The actual binary in the tar.gz file seems to be identical but the helpers like `pagestuff`, etc. are not identical.

I'm currently not feeling comfortable signing this release.

initial build: https://bitcoin.jonasschnelli.ch/gitian/build/78
```
    52eb5b944be4cbba8bdb7fc24641a1ec81c3d5c3f702103683bec431f56aca96  bitcoin-0.20.0rc1-osx-unsigned.dmg
    e890817b186b776e44526c4c3f22bf44483856e6b25ed0a32733205db6d2e4be  bitcoin-0.20.0rc1-osx-unsigned.tar.gz
    b4e6c9c0e0d69dfa98d26c2eab73fd1349491b6debca0d99e65e3d2280ea74b6  bitcoin-0.20.0rc1-osx64.tar.gz
    dc858ec19537f45b4e6e1869f970a86218489acadc31f04c68a700c23124b001  src/bitcoin-0.20.0rc1.tar.gz

    d446d2111ce512da812df9bfad11a30f6259d34e3d484a84b99a3e87abc36cf8  bitcoin-core-osx-0.20-desc.yml
    328aff47e28c17093d59a72712a9b2e62cd8a8b87bbe03f91abb32960b413f0f  MacOSX10.14.sdk.tar.gz
    git:cd1f5bf1db26801a6c266ea1237734ca5ba2c64c bitcoin
```

after re-creating the base image: https://bitcoin.jonasschnelli.ch/gitian/build/86
```
    52eb5b944be4cbba8bdb7fc24641a1ec81c3d5c3f702103683bec431f56aca96  bitcoin-0.20.0rc1-osx-unsigned.dmg
    656580e8835572c9433f9eca53f6d4220b6512b29cc8e06bcac15017b836a96d  bitcoin-0.20.0rc1-osx-unsigned.tar.gz
    b4e6c9c0e0d69dfa98d26c2eab73fd1349491b6debca0d99e65e3d2280ea74b6  bitcoin-0.20.0rc1-osx64.tar.gz
    dc858ec19537f45b4e6e1869f970a86218489acadc31f04c68a700c23124b001  src/bitcoin-0.20.0rc1.tar.gz

    d446d2111ce512da812df9bfad11a30f6259d34e3d484a84b99a3e87abc36cf8  bitcoin-core-osx-0.20-desc.yml
    328aff47e28c17093d59a72712a9b2e62cd8a8b87bbe03f91abb32960b413f0f  MacOSX10.14.sdk.tar.gz
    git:cd1f5bf1db26801a6c266ea1237734ca5ba2c64c bitcoin
```
install log: https://bitcoin.jonasschnelli.ch/gitian/builds/86/install.log

**Comment by jonasschnelli** [comment]
From IRC:
```
[20:53:37]  <achow101> jonasschnelli: it looks like we have different gcc versions
[20:54:03]  <achow101> the .comment section of each of those has GCC: (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0 for you and GCC: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 for me
[20:55:27]  <achow101> how that happened, I'm not sure
```

**Comment by MarcoFalke** [comment]
For linux we explicitly set the gcc version to 8, but macos does none of that.

I believe that @jonasschnelli is using kvm or lxd, which comes with a larger os image with more packages already installed (including gcc 8), whereas @achow101 uses docker, which comes with almost no packages installed (only gcc 7 due to the gitian descriptor).

Somewhere in our configure, it might prefer to pick up gcc 8 over gcc 7.

**Comment by MarcoFalke** [comment]
Huh, don't macos builds use clang instead of gcc?

**Comment by jonasschnelli** [comment]
I think the files that are different are the ones located in `depends/x86_64-apple-darwin16/native/bin` (like `x86_64-apple-darwin16-pagestuff` that gets copied into the .tar.gz file that has the different hash).

I guess the differences origin in the compilation of `native_cctools`.

**Comment by jonasschnelli** [comment]
After clearing the depends cache and resetting the base image, I'm getting the same hash as the rest of the builders: https://bitcoin.jonasschnelli.ch/gitian/build/87

**Comment by jonasschnelli** [comment]
Looks like the reason was pre-installed packaged into the base image for speedup. Resetting the base image and clearing the cache solves it. Closing.
