### ISSUE TITLE
Different hashes for MacOSX10.14.sdk.tar.gz in 0.20 builds

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/gitian.sigs#1223]
Here are hashes of used `MacOSX10.14.sdk.tar.gz`:

`328aff47e28c17093d59a72712a9b2e62cd8a8b87bbe03f91abb32960b413f0f`:
- [laanwj](https://github.com/bitcoin-core/gitian.sigs/blob/master/0.20.0rc1-osx-unsigned/laanwj/bitcoin-core-osx-0.20-build.assert)
- [jonatack](https://github.com/bitcoin-core/gitian.sigs/blob/master/0.20.0rc1-osx-unsigned/jonatack/bitcoin-core-osx-0.20-build.assert)
- [hebasto](https://github.com/bitcoin-core/gitian.sigs/blob/master/0.20.0rc1-osx-unsigned/hebasto/bitcoin-core-osx-0.20-build.assert)
- [fanquake](https://github.com/bitcoin-core/gitian.sigs/blob/master/0.20.0rc1-osx-unsigned/fanquake/bitcoin-core-osx-0.20-build.assert)
- https://bitcoincore.org/depends-sources/sdks/MacOSX10.14.sdk.tar.gz

`ed426758c2fcb7914a7737566f3ac954e4eb6db3beba1fabbe51da94950a28df`:
- [emzy](https://github.com/bitcoin-core/gitian.sigs/blob/master/0.20.0rc1-osx-unsigned/emzy/bitcoin-core-osx-0.20-build.assert)

`bfebab49103d7be9b3a9b85b80a1c0b55dd06f7f991c0df811b009d2fc52def6`:
- [achow101](https://github.com/bitcoin-core/gitian.sigs/blob/master/0.20.0rc1-osx-unsigned/achow101/bitcoin-core-osx-0.20-build.assert)

**Comment by jonasschnelli** [comment]
see: https://github.com/bitcoin-core/gitian.sigs/issues/1222

**Comment by MarcoFalke** [comment]
The sdk is not built deterministically, so expected to diverge in the hash
