### ISSUE TITLE
regex error with parsing name with space

### ISSUE THREAD

**Issue by miketwenty1** [bitcoin-core/gitian.sigs#1316]
https://github.com/bitcoin-core/gitian.sigs/commit/7726206d13b8e451d1799fac910ea8f685557785

Oliver Gugger commit that got pulled in will make something like this return an error due to a regex parsing issue.
`./gitian-builder/bin/gverify -v -d gitian.sigs/ -r ${VERSION}-linux bitcoin/contrib/gitian-descriptors/gitian-linux.yml`

```
./gitian-builder/bin/gverify:22:in `sanitize_path': unsanitary string in signer path (RuntimeError)
```

If we want spaces in the name we would need to edit gitian builder on line 22 to look something like this
`[^@\w\\ '\/.:+-]`
the reason for including the single quote is because git pull will make it 'Oliver Gugger'
PR/fix here if we want to allow spaces.
https://github.com/devrandom/gitian-builder/pull/236

**Comment by guggero** [comment]
Oops... I didn't even notice that I created a folder with spaces in it. Sorry!
It didn't find the signing key locally when I used `guggero`. Any hint on how I can create an alias for it so it won't happen next time?

**Comment by miketwenty1** [comment]
My recommendation would be to use guggero as the folder name.. but then have a comment for gpg that has your actual name. That's what I'm doing. I would defer to @achow101 though.

**Comment by miketwenty1** [comment]
closing this as it's resolved.
