### ISSUE TITLE
Missing GPG keys

### ISSUE THREAD

**Issue by laanwj** [bitcoin-core/gitian.sigs#1427]
While verifying for rc4 I noticed that these keys are not in [keys.txt](https://github.com/bitcoin/bitcoin/blob/master/contrib/gitian-keys/keys.txt).

- [x] `590B7292695AFFA5B672CBB2E13FC145CD3F4304`  @darosior
- [x] `6E01EEC9656903B0542B8F1003DB6322267C373B` @guggero
- [x] `AD5764F4ADCE1B99BDFD179E12335A271D4D62EC`  @miketwenty1
- [x] `0AD83877C1F0CD1EE9BD660AD7CC770B81FD22A8`  @benthecarman
- [x] `6A8F9C266528E25AEB1D7731C2371D91CB716EA7`  @theStack

Glad to see new gitian builders!

If you've done three gitian builds, please add yourself to that file with a PR to the repository.

As an aside, with the gpg keyserver infratstructure being a garbage fire I wonder if it'd make sense to do something to make it easier to get the keys use for gitian signing—and if so, what.

**Comment by benthecarman** [comment]
Added!

**Comment by MarcoFalke** [comment]
> As an aside, with the gpg keyserver infratstructure being a garbage fire I wonder if it'd make sense to do something to make it easier to get the keys use for gitian signing—and if so, what.

https://keys.openpgp.org/ (which checks the email) work fine, no?

**Comment by laanwj** [comment]
Dunno, for example trying to fetch @benthecarman's key:
```
$ gpg --keyserver keys.openpgp.org --recv-key 0AD83877C1F0CD1EE9BD660AD7CC770B81FD22A8
gpg: key 0xD7CC770B81FD22A8: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1
```
I get all kinds of weird errors, timeouts, delays all the time while fetching keys.

**Comment by MarcoFalke** [comment]
I think this error is expected when the email hasn't been confirmed, but I might be wrong.

**Comment by miketwenty1** [comment]
PR submitted Thanks! 
https://github.com/bitcoin/bitcoin/pull/20858

**Comment by miketwenty1** [comment]
https://github.com/bitcoin/bitcoin/pull/20859
PR submitted.

**Comment by laanwj** [comment]
Thanks everyone for submitting your keys, closing.

**Comment by richardsonmark316** [comment]
**8**

**Comment by richardsonmark316** [comment]
‰
