### ISSUE TITLE
Have Travis verify signatures and check for inconsistencies?

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/gitian.sigs#607]
It's probably overkill (and maybe impossible) to have Travis perform an entire Gitian build, but it might be doable to write a script which compares the assert files between contributors and checks their signatures.

**Comment by MeshCollider** [comment]
I've opened a PR for a comparison script, #614 
Would be fairly easy to run gverify too I think but I've left that out for now

**Comment by laanwj** [comment]
I disagree that this is a good idea, see: https://github.com/bitcoin-core/gitian.sigs/pull/614#issuecomment-343653291

A per-merge check that would actually be useful for me (that I have to do every time) is one that makes sure that a user is only committing to one of the subdirectories of the various version directory. E.g. a PR coming from MeshCollider commits to `*/meshcollider/*`. I appreciate that the name mapping is non-obvious though.

**Comment by MeshCollider** [comment]
I think it would be easy enough to make sure all files being touched are within directories with the same name (e.g. if I submit sigs in */meshcollider/* and also touch a file in laanwj/ it would fail). The number of gitian builders is probably small enough that a github username -> signing name table could probably be hardcoded in somewhere though right?

**Comment by MarcoFalke** [comment]
The simplest check would be to assert that each commit only adds files. It should be never required to delete files and very rarely to modify files, so I think that false positive rate is acceptable.

**Comment by MeshCollider** [comment]
@wumpus see https://github.com/bitcoin-core/gitian.sigs/pull/678 for a script which does what you suggest

**Comment by wumpus** [comment]
I'd suggest asking the correct wumpus.

**Comment by Sjors** [comment]
Aka @laanwj

**Comment by MeshCollider** [comment]
Heh oops, switching between IRC and github too quickly
